table 'olist_payments_clean (2)'
	lineageTag: 7bc88e46-2960-4fc1-8bb8-007a71f4e034

	column order_id
		dataType: string
		lineageTag: 56b495fb-f716-450b-b17b-d43b8e94f1d8
		summarizeBy: none
		sourceColumn: order_id

		annotation SummarizationSetBy = Automatic

	column payment_type
		dataType: string
		lineageTag: aca1eba9-3bb6-4012-aa2c-c94ff59465a9
		summarizeBy: none
		sourceColumn: payment_type

		annotation SummarizationSetBy = Automatic

	column payment_value
		dataType: double
		lineageTag: e21f4e78-6331-4025-9299-d5cf1487a2c6
		summarizeBy: sum
		sourceColumn: payment_value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'olist_payments_clean (2)' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\MSI\Desktop\Data Project\Olist\04_Customer_Behavior_and_Statistical_Testing\olist_payments_clean.csv"),[Delimiter=",", Columns=3, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"order_id", type text}, {"payment_type", type text}, {"payment_value", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

